/**
 * Shared domain types for Harness Dreams.
 *
 * Vocabulary mirrors the product spec in `md/`: a harness "sleeps", a Dream
 * Session produces a Dream Report (vitals + findings + suggested improvements),
 * and the user "reflects" each morning.
 */

/** Where the overnight reflection currently is. Drives the menu-bar icon. */
export type DreamPhase = "resting" | "dreaming" | "ready";

/** Local-first by default; cloud analysis is an explicit opt-in. */
export type PrivacyMode = "local" | "cloud";

/** How deep the opt-in REM analysis pass goes. */
export type AnalysisDepth = "light" | "standard" | "deep";

/** When dreams run. */
export type ScheduleMode = "nightly" | "manual";
export type AnalysisSource = "claude-code" | "codex" | "code";
export type RemRunnerProvider = "claude-code" | "codex";

export interface RemRunnerConfig {
  provider: RemRunnerProvider;
  model: string;
  claudePath: string;
  codexPath: string;
  timeoutMs: number;
}

export type CloudSyncDeviceKind = "iphone" | "ipad" | "watch";
export type CloudSyncDeviceStatus = "pending" | "active" | "revoked";

export interface CloudSyncDevice {
  deviceId: string;
  deviceName: string;
  kind: CloudSyncDeviceKind;
  status: CloudSyncDeviceStatus;
  tokenHash: string;
  createdAt: number;
  lastTokenIssuedAt: number;
  lastSeenAt?: number;
  revokedAt?: number;
}

export interface CloudSyncPairing {
  token: string;
  pairingUrl: string;
  qrDataUrl: string;
  expiresAt: number;
  device: CloudSyncDevice;
}

export interface CloudSyncConfig {
  enabled: boolean;
  /** Paid-plan entitlement. Dev builds can bypass this with devBypassPaidPlan. */
  paidPlan: boolean;
  /** Dev/demo override so the paid gate does not block local demos. */
  devBypassPaidPlan: boolean;
  /** MongoDB Atlas connection string. May be left blank to use env vars. */
  atlasUri: string;
  /** Atlas database used for cycle snapshots and decisions. */
  databaseName: string;
  /** Stable app-level user id generated by the desktop; no account required. */
  userId: string;
  /** HMAC secret used by the desktop to issue device-pairing JWTs. */
  jwtSecret: string;
  /** Stable id for this desktop install. Generated on first launch. */
  deviceId: string;
  deviceName: string;
  /** Poll fallback interval; change streams run when Atlas supports them. */
  syncIntervalMs: number;
  /** Devices paired by QR code. Removing a device makes future writes ignored. */
  devices: CloudSyncDevice[];
}

export type CloudSyncState =
  | "disabled"
  | "needs-setup"
  | "connecting"
  | "syncing"
  | "watching"
  | "offline"
  | "error";

export interface CloudSyncStatus {
  enabled: boolean;
  paidPlan: boolean;
  devBypassPaidPlan: boolean;
  allowedByPlan: boolean;
  configured: boolean;
  state: CloudSyncState;
  message: string;
  userId: string;
  deviceId: string;
  databaseName: string;
  collections: {
    cycles: string;
    decisions: string;
    devices: string;
  };
  lastSyncedAt: number | null;
  lastPulledAt: number | null;
  lastPushedAt: number | null;
  nextSyncAt: number | null;
  localSyncUrl?: string;
  cyclesPushed: number;
  decisionsPushed: number;
  remoteDecisionsApplied: number;
  lastError?: string;
}

export interface AnalysisProject {
  path: string;
  name: string;
  sources: AnalysisSource[];
  enabled: boolean;
  addedAt: number;
}

export interface DiscoveredProject {
  path: string;
  name: string;
  sources: AnalysisSource[];
  sessionCount: number;
  lastActivityAt: number | null;
}

/** Persisted, user-facing configuration. */
export interface AppConfig {
  onboarded: boolean;
  /** Use persisted fictional projects/cycles for product demos and walkthroughs. */
  demoMode: boolean;
  /** Replay the welcome/setup flow on every app launch (until turned off). */
  showOnboardingOnLaunch: boolean;
  privacyMode: PrivacyMode;
  schedule: {
    mode: ScheduleMode;
    /** 24h "HH:MM" — when the nightly dream runs. */
    time: string;
  };
  notifications: boolean;
  analysisDepth: AnalysisDepth;
  /** CLI runner used for opt-in cloud REM analysis. */
  remRunner: RemRunnerConfig;
  launchAtLogin: boolean;
  /** Honor the OS reduced-motion preference, or force it on. */
  reduceMotion: boolean;
  /** Self-hosted MongoDB Atlas sync for cycle signal + action choices. */
  cloudSync: CloudSyncConfig;
  /**
   * Legacy interest flag from the pre-Atlas upgrade flow. Kept so older config
   * files migrate cleanly; `cloudSync.enabled` now controls live sync.
   */
  cloudSyncInterest: boolean;
  /** Which harnesses we (will) ingest. Claude Code ships first. */
  connectors: {
    claudeCode: boolean;
    codex: boolean;
    cursor: boolean;
  };
  projects: AnalysisProject[];
}

/** Live, non-persisted runtime state broadcast to the UI. */
export interface RuntimeState {
  phase: DreamPhase;
  /** 0..1 while phase === "dreaming". */
  progress: number;
  /** Current dream stage label while dreaming, else null. */
  stage: string | null;
  /** True when a running dream is paused. */
  paused: boolean;
  /** Epoch ms of the last completed dream, or null. */
  lastDreamAt: number | null;
  /** True when a fresh dream hasn't been opened yet (drives the badge). */
  hasUnreviewed: boolean;
}

// ── Dream Report ─────────────────────────────────────────────────────────────

export type RingKey = "efficiency" | "effectiveness" | "alignment";

/** One of the three Apple-Health-style headline scores (0..100). */
export interface Ring {
  key: RingKey;
  label: string;
  score: number;
  /** Change vs the user's rolling baseline, in points. */
  delta: number;
  hint: string;
}

export type Trend = "up" | "down" | "flat";

/** A headline vital shown in the metrics strip. */
export interface Metric {
  key: string;
  label: string;
  value: string;
  /** Percent change vs baseline. */
  delta: number;
  trend: Trend;
  /** Whether the trend direction is good (green) or not (amber). */
  good: boolean;
}

export type FindingType = "win" | "mistake" | "opportunity" | "risk";
export type Confidence = "low" | "medium" | "high";

export interface Finding {
  id: string;
  type: FindingType;
  title: string;
  body: string;
  /** Plain-language improvement suggested by the finding. */
  improvement: string;
  /** How the harness/agent behavior should improve. */
  agentBenefit: string;
  /** How the user's workflow should improve. */
  userBenefit: string;
  /** What the next report should keep checking. */
  reflection: string;
  confidence: Confidence;
  project: string;
  /** One-line pointer to the evidence. */
  evidence: string;
  /** Absolute transcript path containing the evidence, when available. */
  evidenceFile?: string;
  /** The precise config-vs-behavior gap the finding addresses. */
  configGap?: string;
  /** The single recommended next step. */
  action: string;
  /** Optional action category hint; the UI derives one when absent. */
  category?: ActionCategory;
  /** Optional friction classification; only meaningful for mistake/risk. */
  frictionType?: FrictionType;
  /** Absolute path of the project this finding came from (for applying patches). */
  projectPath?: string;
  /** A concrete file change this recommendation would apply if accepted. */
  patch?: ConfigPatchPreview;
}

/**
 * A concrete, ready-to-apply change a recommendation would make — the actual
 * file and the managed snippet written into it. This is what turns a finding
 * into a "true AGENTS.md / skill improvement" rather than generic advice.
 */
export interface ConfigPatchPreview {
  /** Where the patch lands. */
  target: ActionCategory;
  /** Absolute path of the file the patch touches (AGENTS.md / CLAUDE.md / skill). */
  file: string;
  /** Short human label, e.g. "AGENTS.md · my-project" or "New skill · deploy". */
  label: string;
  /** The exact block/snippet that would be inserted or created. */
  snippet: string;
  /** True when the file would be created from scratch. */
  creates: boolean;
}

export type ContextSourceKind =
  | "agentsmd"
  | "claudemd"
  | "rules"
  | "memory"
  | "skill"
  | "codex-home"
  | "claude-home"
  | "settings";

export type ContextHealthStatus = "clear" | "watch" | "overloaded";

/** A small, non-content inventory of context a harness may load. */
export interface ContextSourceSummary {
  kind: ContextSourceKind;
  label: string;
  path: string;
  chars: number;
  lines: number;
}

/** Deterministic context-hygiene score for a project plus home harness config. */
export interface ContextHealth {
  score: number;
  status: ContextHealthStatus;
  totalChars: number;
  projectChars: number;
  globalChars: number;
  memoryChars: number;
  skillCount: number;
  localSkillCount: number;
  globalSkillCount: number;
  hasRulesMd: boolean;
  memoryFiles: number;
  sourceCount: number;
  oversizedFiles: ContextSourceSummary[];
  risks: string[];
  suggestions: string[];
}

// ── Human ↔ Agent alignment (additive; UI derives fallbacks when absent) ──────

/** Where a cycle sits on the collaboration spectrum. */
export type AlignmentBand = "collaborating" | "friction" | "fighting";

/** Where a recommended action should land. */
export type ActionCategory =
  | "agentsmd" // "AGENTS.md update"
  | "claudemd" // "CLAUDE.md update"
  | "contextdoc" // "Context doc"
  | "prompthabit" // "Prompt habit"
  | "skill"; // "Skill / routing"

/** A user's decision on a finding's recommended action. */
export type ActionState =
  "open" | "accepted" | "rejected" | "snoozed" | "queued";

/** The kind of friction a finding surfaced between human and agent. */
export type FrictionType =
  "config-conflict" | "missing-skill" | "wrong-domain" | "unclear-prompt";

/** A single point of friction, linked 1:1 to the finding that explains it. */
export interface FrictionPoint {
  type: FrictionType;
  /** One-line, drawn from a finding's evidence. */
  example: string;
  /** Links to the Finding this friction explains. */
  findingId: string;
}

/** One half of the alignment picture — the human's or the agent's. */
export interface AlignmentSide {
  /** human: deep-focus|exploratory|scattered|frustrated.
   *  agent: confident|uncertain|confused|overloaded. */
  mood: string;
  /** The implicit question held all day. */
  question: string;
  /** Evidence chips. */
  signals: string[];
}

/** The full alignment detail for a cycle; mirrors the `alignment` ring. */
export interface AlignmentDetail {
  /** 0..100; mirrors the `alignment` ring score. */
  score: number;
  band: AlignmentBand;
  human: AlignmentSide;
  agent: AlignmentSide;
  friction: FrictionPoint[];
}

/** A finding's recommended action after a Sleep Cycle review decision. */
export interface ActionQueueEntry {
  findingId: string;
  category: ActionCategory;
  /** The recommended step (finding.action). */
  action: string;
  project: string;
  /** accepted | rejected | queued | snoozed (open entries are not summarized). */
  state: ActionState;
  /** Last time this decision changed, used for sync conflict resolution. */
  decidedAt?: number;
  /** Device that last wrote the decision. */
  sourceDeviceId?: string;
  sourceDeviceName?: string;
  /** Absolute path of the originating project, when known. */
  projectPath?: string;
  /** The concrete file change this entry applies if accepted. */
  patch?: ConfigPatchPreview;
  /** Feature branch / PR metadata created when the recommendation is accepted. */
  reviewBranch?: {
    branch: string;
    baseBranch?: string;
    worktreePath?: string;
    commit?: string;
    remote?: string;
    prUrl?: string;
    pushed: boolean;
    error?: string;
  };
}

export interface SyncedReviewDecision {
  reportId: string;
  findingId: string;
  state: Exclude<ActionState, "open">;
  updatedAt: number;
  sourceDeviceId: string;
  sourceDeviceName?: string;
  deviceTokenHash?: string;
}

/** Basis for the activity window a Sleep Cycle reviewed. */
export type WindowBasis = "since-last-cycle" | "last-24h";

/**
 * The slice of time a Sleep Cycle actually reviewed: everything since the last
 * cycle, capped at 24 hours. This is what makes a cycle a true incremental
 * review rather than a re-scan of all history.
 */
export interface CycleWindow {
  /** Epoch ms — window start. */
  start: number;
  /** Epoch ms — window end (when the cycle ran). */
  end: number;
  basis: WindowBasis;
  /** Human label, e.g. "Since 9:40 PM · 3h 12m of activity". */
  label: string;
  /** Sessions with activity inside the window. */
  sessionsInWindow: number;
  /** User+agent turns inside the window. */
  turnsInWindow: number;
}

/** A per-project rollup of what happened inside the cycle window. */
export interface ProjectInsight {
  name: string;
  path: string;
  sources: AnalysisSource[];
  sessions: number;
  turns: number;
  /** Rapid user follow-ups / corrections. */
  corrections: number;
  /** Tool calls that surfaced an error. */
  toolFailures: number;
  /** Agent uncertainty signals. */
  hedges: number;
  /** 0..100 local alignment for this project alone. */
  alignment: number;
  /** Top recurring topics, most frequent first. */
  topics: string[];
  hasAgentsMd: boolean;
  hasClaudeMd: boolean;
  hasRulesMd?: boolean;
  skillCount: number;
  /** Deterministic context-load and memory hygiene signal. */
  contextHealth?: ContextHealth;
}

/** Decisions captured during review, keyed by finding id. */
export type ReviewDecisions = Record<string, ActionState>;

/** User-facing lifecycle for a cycle report. */
export type CycleReviewStatus = "unreviewed" | "reviewed" | "expired";

export type ExperimentStatus = "proposed" | "running" | "concluded";
export type ExperimentVerdict = "helped" | "no-change" | "worse";

export interface Experiment {
  id: string;
  title: string;
  hypothesis: string;
  agentBenefit: string;
  userBenefit: string;
  reflection: string;
  metric: string;
  status: ExperimentStatus;
  /** 0..1 for tracked improvements ("4/5 sessions"). */
  progress?: number;
  progressLabel?: string;
  verdict?: ExperimentVerdict;
  verdictNote?: string;
  /** Which project this goal targets, so the next cycle can measure it. */
  projectPath?: string;
  /** Where the accepted change landed. */
  category?: ActionCategory;
  /**
   * Snapshot of the target project at the moment the goal was accepted. The
   * next cycle compares against this to decide whether the change helped.
   */
  baseline?: { alignment: number; corrections: number; contextScore?: number };
}

/** The artifact a Dream Session produces — styled like the Apple Health app. */
export interface DreamReport {
  id: string;
  /** Epoch ms the dream completed — used for ordering and history labels. */
  timestamp: number;
  /** Review lifecycle. Starting a newer cycle expires older unreviewed cycles. */
  reviewStatus?: CycleReviewStatus;
  /** Epoch ms when the user marked the cycle reviewed. */
  reviewedAt?: number;
  /** Human label, e.g. "Last night · Jun 26". */
  rangeLabel: string;
  sessions: number;
  projects: number;
  harness: string;
  digest: string;
  rings: Ring[];
  metrics: Metric[];
  findings: Finding[];
  /** Tracked suggested improvements; stored as experiments for measurement. */
  experiments: Experiment[];
  /** Persisted Sleep Cycle review decisions, if the user has reviewed it. */
  reviewDecisions?: ActionQueueEntry[];
  /** Human ↔ Agent alignment detail; optional — UI derives a fallback if absent. */
  alignment?: AlignmentDetail;
  /** The activity window this cycle reviewed (since last cycle, capped 24h). */
  window?: CycleWindow;
  /** Per-project rollups inside the window, most active first. */
  projectInsights?: ProjectInsight[];
  /** Report-level context hygiene summary across reviewed projects. */
  contextHealth?: {
    score: number;
    status: ContextHealthStatus;
    overloadedProjects: number;
    riskCount: number;
    chars: number;
    memoryFiles: number;
    skillCount: number;
    suggestions: string[];
  };
  /** Redacted CLI payload summary for opt-in cloud REM analysis. */
  cloudRedactionPreview?: {
    runner: string;
    model: string;
    redactions: number;
    payloadChars: number;
    projects: number;
    error?: string;
  };
}
