/**
 * Shared domain types for Harness Health.
 *
 * Vocabulary mirrors the product pivot: live harness telemetry produces daily
 * health reviews, vitals, findings, habits, and suggested improvements.
 */

/** Where the current health review run is. Drives the menu-bar icon. */
export type HealthReviewPhase = "idle" | "running" | "ready";

/**
 * What kind of health review is running. A full review is the daily baseline
 * pass; a quick review is a lighter same-day check-in with only the top nudges.
 */
export type HealthReviewKind = "full" | "quick";

/** Local-first by default; cloud analysis is an explicit opt-in. */
export type PrivacyMode = "local" | "cloud";

/** How deep the opt-in AI insight analysis pass goes. */
export type AnalysisDepth = "light" | "standard" | "deep";
export type GuidanceApplyMode = "branch" | "direct";

/** When health reviews run. */
export type ScheduleMode = "daily" | "manual";
export type AnalysisSource = "claude-code" | "codex" | "code";
export type InsightRunnerProvider = "claude-code" | "codex";

export interface InsightRunnerConfig {
  provider: InsightRunnerProvider;
  model: string;
  claudePath: string;
  codexPath: string;
  timeoutMs: number;
}

export interface TelemetryPricePoint {
  inputPerMTok: number;
  outputPerMTok: number;
  cacheReadPerMTok?: number;
  cacheCreatePerMTok?: number;
}

export interface TelemetryConfig {
  enabled: boolean;
  watch: boolean;
  retentionDays: number;
  rawTextRetention: boolean;
  priceTable: Record<string, TelemetryPricePoint>;
}

export type CloudSyncDeviceKind = "desktop" | "iphone" | "ipad" | "watch";
export type CloudSyncDeviceStatus = "pending" | "active" | "revoked";

export interface CloudSyncDevice {
  deviceId: string;
  deviceName: string;
  kind: CloudSyncDeviceKind;
  status: CloudSyncDeviceStatus;
  /** Hash of the per-device shared secret. */
  secretHash: string;
  /** Local encrypted copy of the per-device shared secret. Never sent to Cloudflare. */
  secretCiphertext?: string;
  createdAt: number;
  /** When this device secret was issued. */
  secretIssuedAt: number;
  lastSeenAt?: number;
  revokedAt?: number;
  lastAckedRevision?: number;
}

export interface BackupKeyRecord {
  keyId: string;
  backupKey: string;
  backupEpochId: string;
  retiredAt: number;
}

export interface CloudSyncPairing {
  pairingId: string;
  pairingUrl: string;
  cloudApiBaseUrl: string;
  secret: string;
  backupEnabled: boolean;
  qrDataUrl: string;
  expiresAt: number;
  device: CloudSyncDevice;
}

export interface CloudSyncConfig {
  enabled: boolean;
  /** Paid-plan entitlement. Dev builds can bypass this with devBypassPaidPlan. */
  paidPlan: boolean;
  /** Dev/demo override so the paid gate does not block local demos. */
  devBypassPaidPlan: boolean;
  /** Cloudflare Worker base URL used only for ephemeral WebRTC signaling. */
  cloudApiBaseUrl: string;
  /** Stable app-level user id generated by the desktop; no account required. */
  cloudUserId: string;
  /** Stable id for this desktop install. Generated on first launch. */
  deviceId: string;
  deviceName: string;
  /** Devices paired by QR code. Removing a device prevents future reconnects. */
  devices: CloudSyncDevice[];
  /** Optional encrypted cloud fallback for when this Mac is offline. */
  backupEnabled: boolean;
  /** Local-only snapshot backup encryption key. Shared only through QR/WebRTC. */
  backupKey: string;
  /** Identifier for the current snapshot backup key. */
  backupKeyId: string;
  /** Locally retained retired keys for decrypting older backup packages. */
  backupRetainedKeys: BackupKeyRecord[];
  /** Rotated when backup access is reset/revoked. */
  backupEpochId: string;
  /** Encrypted backup retention window. */
  backupRetentionDays: number;
  lastBackupAt?: number;
  lastBackupRevision?: number;
  lastBackupFailureAt?: number;
  lastBackupFailureRevision?: number;
  nextBackupRetryAt?: number;
  backupRetryAttempt?: number;
  lastBackupError?: string;
}

export type CloudSyncState =
  | "disabled"
  | "needs-setup"
  | "connecting"
  | "syncing"
  | "watching"
  | "offline"
  | "error";

export interface CloudSyncStatus {
  enabled: boolean;
  paidPlan: boolean;
  devBypassPaidPlan: boolean;
  allowedByPlan: boolean;
  configured: boolean;
  state: CloudSyncState;
  message: string;
  cloudUserId: string;
  deviceId: string;
  cloudApiBaseUrl: string;
  lastSyncedAt: number | null;
  lastPulledAt: number | null;
  lastPushedAt: number | null;
  nextSyncAt: number | null;
  reviewsPushed: number;
  decisionsPushed: number;
  remoteDecisionsApplied: number;
  activeConnections: number;
  pairingActive: boolean;
  iceMode: "unknown" | "stun" | "turn";
  revision: number;
  backupEnabled: boolean;
  backupConfigured: boolean;
  backupRevision: number;
  backupKeyId: string;
  lastBackedUpAt: number | null;
  lastBackupFailureAt: number | null;
  nextBackupRetryAt: number | null;
  backupRetryAttempt: number;
  lastError?: string;
}

export interface PeerHostDevice {
  deviceId: string;
  deviceName: string;
  kind: CloudSyncDeviceKind;
  status: CloudSyncDeviceStatus;
  sharedSecret: string;
  lastSeenAt?: number;
  lastAckedRevision?: number;
}

export interface PeerHostPairingSession {
  pairingId: string;
  secret: string;
  expiresAt: number;
  device: CloudSyncDevice;
}

export interface PeerHostState {
  enabled: boolean;
  allowedByPlan: boolean;
  signalUrl: string;
  cloudUserId: string;
  desktopDeviceId: string;
  desktopDeviceName: string;
  devices: PeerHostDevice[];
  pairingSessions: PeerHostPairingSession[];
  reports: HealthReport[];
  revision: number;
  backupEnabled: boolean;
  backupEpochId: string;
  backupKey: string;
  backupKeyId: string;
}

export interface PeerHostPairingAccepted {
  pairingId: string;
  deviceId: string;
  deviceName: string;
  kind: CloudSyncDeviceKind;
  pairedDeviceSecret: string;
}

export interface PeerHostConnectionUpdate {
  deviceId: string;
  connected: boolean;
  lastSeenAt?: number;
  iceMode?: "unknown" | "stun" | "turn";
  lastAckedRevision?: number;
  error?: string;
}

export interface AnalysisProject {
  path: string;
  name: string;
  sources: AnalysisSource[];
  enabled: boolean;
  addedAt: number;
}

export interface DiscoveredProject {
  path: string;
  name: string;
  sources: AnalysisSource[];
  sessionCount: number;
  lastActivityAt: number | null;
}

/** Persisted, user-facing configuration. */
export interface AppConfig {
  onboarded: boolean;
  /** What the app calls the user in greetings. Empty until they tell us. */
  userName: string;
  /** Use persisted fictional projects/reviews for product demos and walkthroughs. */
  demoMode: boolean;
  /** Replay the welcome/setup flow on every app launch (until turned off). */
  showOnboardingOnLaunch: boolean;
  privacyMode: PrivacyMode;
  schedule: {
    mode: ScheduleMode;
    /** 24h "HH:MM" — when the daily review runs. */
    time: string;
  };
  notifications: boolean;
  analysisDepth: AnalysisDepth;
  /** How accepted guidance changes are applied after review. */
  guidanceApplyMode: GuidanceApplyMode;
  /** CLI runner used for opt-in AI insight analysis. */
  insightRunner: InsightRunnerConfig;
  /** Local-first realtime Harness Health telemetry. */
  telemetry: TelemetryConfig;
  launchAtLogin: boolean;
  /** Honor the OS reduced-motion preference, or force it on. */
  reduceMotion: boolean;
  /** Private device sync: Cloudflare is only ephemeral WebRTC signaling. */
  cloudSync: CloudSyncConfig;
  /** Interest flag from the upgrade flow; `cloudSync.enabled` controls live sync. */
  companionSyncInterest: boolean;
  /** Which harnesses we (will) ingest. Claude Code ships first. */
  connectors: {
    claudeCode: boolean;
    codex: boolean;
    cursor: boolean;
  };
  projects: AnalysisProject[];
}

/** Live, non-persisted runtime state broadcast to the UI. */
export interface RuntimeState {
  phase: HealthReviewPhase;
  /** 0..1 while phase === "running". */
  progress: number;
  /** Current review stage label while running, else null. */
  stage: string | null;
  /** True when a running review is paused. */
  paused: boolean;
  /** Epoch ms of the last completed review, or null. */
  lastReviewAt: number | null;
  /** True when a fresh review hasn't been opened yet (drives the badge). */
  hasUnreviewed: boolean;
}

// ── Health Report ─────────────────────────────────────────────────────────────

export type RingKey = "efficiency" | "effectiveness" | "alignment";

/** One of the three Apple-Health-style headline scores (0..100). */
export interface Ring {
  key: RingKey;
  label: string;
  score: number;
  /** Change vs the user's rolling baseline, in points. */
  delta: number;
  hint: string;
}

export type Trend = "up" | "down" | "flat";

/** A headline vital shown in the metrics strip. */
export interface Metric {
  key: string;
  /** Canonical metric id from the normalized telemetry catalog. */
  canonicalKey?: string;
  label: string;
  value: string;
  /** Raw numeric value used by companion clients for truthful charts. */
  numericValue?: number;
  unit?: string;
  /** Percent change vs baseline. */
  delta: number;
  trend: Trend;
  /** Whether the trend direction is good (green) or not (amber). */
  good: boolean;
  samples?: Array<{
    label: string;
    value: number;
    display?: string;
    sourceCount?: number;
  }>;
  /** Number of normalized source events/samples behind the metric. */
  sourceCount?: number;
  /** Confidence in the current value/baseline comparison. */
  confidence?: "low" | "medium" | "high";
  /** Short provenance note for source transparency. */
  provenance?: string;
}

// ── Realtime Harness Health telemetry ───────────────────────────────────────

export type HarnessKind = "claude-code" | "codex" | "cursor" | "code";

export type NormalizedEventKind =
  | "user_prompt"
  | "assistant_message"
  | "model_call"
  | "tool_call"
  | "tool_result"
  | "file_edit"
  | "command_run"
  | "error"
  | "guardrail_hit"
  | "permission_decision"
  | "skill_invocation"
  | "mcp_call"
  | "mode_change"
  | "meta";

export interface SessionRef {
  id: string;
  source: HarnessKind;
  filePath: string;
  projectPath: string;
  projectName: string;
  mtimeMs: number;
  size: number;
}

export interface IngestCursor {
  filePath: string;
  source: HarnessKind;
  connectorVersion: string;
  size: number;
  mtimeMs: number;
  lineOffset: number;
  byteOffset: number;
  updatedAt: number;
}

export interface NormalizedEvent {
  id: string;
  source: HarnessKind;
  connectorVersion: string;
  sessionId: string;
  projectPath: string;
  projectName: string;
  ts: number;
  seq: number;
  kind: NormalizedEventKind;
  role?: "user" | "assistant" | "system";
  model?: string;
  tokensIn?: number;
  tokensOut?: number;
  cacheReadTokens?: number;
  cacheCreateTokens?: number;
  toolName?: string;
  mcpServer?: string;
  mcpTool?: string;
  toolOutcome?: "ok" | "error" | "denied";
  permissionMode?: string;
  latencyMs?: number;
  speed?: number;
  iterations?: number;
  rawPath: string;
  rawLine: number;
}

export interface MetricDefinition {
  id: string;
  label: string;
  category:
    | "efficiency"
    | "effectiveness"
    | "alignment"
    | "context"
    | "models"
    | "tools"
    | "config";
  unit: string;
  valueKind: "quantity" | "category" | "duration" | "event" | "ratio";
  aggregation: "sum" | "avg" | "min" | "max" | "latest" | "count";
  direction: "up" | "down" | "contextual";
  description: string;
}

export interface MetricSample {
  metricId: string;
  value: number;
  unit: string;
  startAt: number;
  endAt: number;
  sourceCount: number;
}

export interface ConfigArtifact {
  id: string;
  kind:
    | "agents-md"
    | "claude-md"
    | "rules"
    | "skill"
    | "mcp"
    | "settings"
    | "memory"
    | "hook"
    | "harness"
    | "other";
  path: string;
  label: string;
  chars: number;
  lines: number;
  hash: string;
  lastReadAt: number;
  source: "project" | "home" | "harness";
}

export interface LiveInsight {
  id: string;
  metricIds: string[];
  type: "trend" | "anomaly" | "milestone" | "consistency" | "recommendation";
  severity: "positive" | "neutral" | "warning";
  title: string;
  explanation: string;
  recommendation?: string;
  comparison: {
    currentWindow: { start: number; end: number };
    baselineWindow?: { start: number; end: number };
    delta?: number;
    deltaPercent?: number;
  };
  confidence: "low" | "medium" | "high";
  sourceSampleCount: number;
  deepLink: string;
  createdAt: number;
}

export interface LiveTelemetrySource {
  source: HarnessKind;
  label: string;
  status: "watching" | "scanning" | "missing" | "error";
  files: number;
  events: number;
  sessions: number;
  lastActivityAt: number | null;
  message?: string;
}

export interface LiveProjectTelemetry {
  path: string;
  name: string;
  sources: HarnessKind[];
  sessions: number;
  events: number;
  tokens: number;
  corrections: number;
  toolFailures: number;
  lastActivityAt: number | null;
  contextScore?: number;
}

export interface LiveModelUsage {
  model: string;
  tokens: number;
  sessions: number;
  source: HarnessKind;
  share: number;
}

export interface LiveTrendPoint {
  start: number;
  end: number;
  label: string;
  tokens: number;
  sessions: number;
  corrections: number;
  toolFailures: number;
}

export interface IngestStatus {
  state: "idle" | "scanning" | "watching" | "error";
  message: string;
  startedAt: number | null;
  finishedAt: number | null;
  filesDiscovered: number;
  filesChanged: number;
  eventsIngested: number;
  cursorsUpdated: number;
  lastError?: string;
}

export interface LiveTelemetrySnapshot {
  generatedAt: number;
  window: { start: number; end: number; label: string };
  baselineWindow: { start: number; end: number; label: string };
  rings: Ring[];
  metrics: Metric[];
  insights: LiveInsight[];
  sources: LiveTelemetrySource[];
  activeProjects: LiveProjectTelemetry[];
  modelMix: LiveModelUsage[];
  trendSeries: LiveTrendPoint[];
  configArtifacts: ConfigArtifact[];
  status: IngestStatus;
}

export interface LiveMetricDetail {
  metricId: string;
  label: string;
  unit: string;
  current: MetricSample;
  baseline?: MetricSample;
  samples: MetricSample[];
  sources: LiveTelemetrySource[];
  insights: LiveInsight[];
}

export type FindingType = "win" | "mistake" | "opportunity" | "risk";
export type Confidence = "low" | "medium" | "high";

export interface Finding {
  id: string;
  type: FindingType;
  title: string;
  body: string;
  /** Plain-language improvement suggested by the finding. */
  improvement: string;
  /** How the harness/agent behavior should improve. */
  agentBenefit: string;
  /** How the user's workflow should improve. */
  userBenefit: string;
  /** What the next report should keep checking. */
  reflection: string;
  confidence: Confidence;
  project: string;
  /** One-line pointer to the evidence. */
  evidence: string;
  /** Absolute transcript path containing the evidence, when available. */
  evidenceFile?: string;
  /** The precise config-vs-behavior gap the finding addresses. */
  configGap?: string;
  /** The single recommended next step. */
  action: string;
  /** Optional action category hint; the UI derives one when absent. */
  category?: ActionCategory;
  /** Optional friction classification; only meaningful for mistake/risk. */
  frictionType?: FrictionType;
  /** Absolute path of the project this finding came from (for applying patches). */
  projectPath?: string;
  /** A concrete file change this recommendation would apply if accepted. */
  patch?: ConfigPatchPreview;
}

/**
 * A concrete, ready-to-apply change a recommendation would make — the actual
 * file and the managed snippet written into it. This is what turns a finding
 * into a "true AGENTS.md / skill improvement" rather than generic advice.
 */
export interface ConfigPatchPreview {
  /** Where the patch lands. */
  target: ActionCategory;
  /** Absolute path of the file the patch touches (AGENTS.md / CLAUDE.md / skill). */
  file: string;
  /** Short human label, e.g. "AGENTS.md · my-project" or "New skill · deploy". */
  label: string;
  /** The exact block/snippet that would be inserted or created. */
  snippet: string;
  /** True when the file would be created from scratch. */
  creates: boolean;
}

export type ContextSourceKind =
  | "agentsmd"
  | "claudemd"
  | "rules"
  | "memory"
  | "skill"
  | "codex-home"
  | "claude-home"
  | "settings";

export type ContextHealthStatus = "clear" | "watch" | "overloaded";

/** A small, non-content inventory of context a harness may load. */
export interface ContextSourceSummary {
  kind: ContextSourceKind;
  label: string;
  path: string;
  chars: number;
  lines: number;
}

/** Deterministic context-hygiene score for a project plus home harness config. */
export interface ContextHealth {
  score: number;
  status: ContextHealthStatus;
  totalChars: number;
  projectChars: number;
  globalChars: number;
  memoryChars: number;
  skillCount: number;
  localSkillCount: number;
  globalSkillCount: number;
  hasRulesMd: boolean;
  memoryFiles: number;
  sourceCount: number;
  oversizedFiles: ContextSourceSummary[];
  risks: string[];
  suggestions: string[];
}

// ── Human ↔ Agent alignment (additive; UI derives fallbacks when absent) ──────

/** Where a review sits on the collaboration spectrum. */
export type AlignmentBand = "collaborating" | "friction" | "fighting";

/** Where a recommended action should land. */
export type ActionCategory =
  | "agentsmd" // "AGENTS.md update"
  | "claudemd" // "CLAUDE.md update"
  | "contextdoc" // "Context doc"
  | "prompthabit" // "Prompt habit"
  | "skill"; // "Skill / routing"

/** A user's decision on a finding's recommended action. */
export type ActionState =
  | "open"
  | "accepted"
  | "rejected"
  | "snoozed"
  | "queued";

/** The kind of friction a finding surfaced between human and agent. */
export type FrictionType =
  | "config-conflict"
  | "missing-skill"
  | "wrong-domain"
  | "unclear-prompt";

/** A single point of friction, linked 1:1 to the finding that explains it. */
export interface FrictionPoint {
  type: FrictionType;
  /** One-line, drawn from a finding's evidence. */
  example: string;
  /** Links to the Finding this friction explains. */
  findingId: string;
}

/** One half of the alignment picture — the human's or the agent's. */
export interface AlignmentSide {
  /** human: deep-focus|exploratory|scattered|frustrated.
   *  agent: confident|uncertain|confused|overloaded. */
  mood: string;
  /** The implicit question held all day. */
  question: string;
  /** Evidence chips. */
  signals: string[];
}

/** The full alignment detail for a review; mirrors the `alignment` ring. */
export interface AlignmentDetail {
  /** 0..100; mirrors the `alignment` ring score. */
  score: number;
  band: AlignmentBand;
  human: AlignmentSide;
  agent: AlignmentSide;
  friction: FrictionPoint[];
}

/** A finding's recommended action after a Health Review decision. */
export interface ActionQueueEntry {
  findingId: string;
  category: ActionCategory;
  /** The recommended step (finding.action). */
  action: string;
  project: string;
  /** accepted | rejected | queued | snoozed (open entries are not summarized). */
  state: ActionState;
  /** Last time this decision changed, used for sync conflict resolution. */
  decidedAt?: number;
  /** Device that last wrote the decision. */
  sourceDeviceId?: string;
  sourceDeviceName?: string;
  /** Absolute path of the originating project, when known. */
  projectPath?: string;
  /** The concrete file change this entry applies if accepted. */
  patch?: ConfigPatchPreview;
  /** Feature branch / PR metadata created when the recommendation is accepted. */
  reviewBranch?: {
    mode?: GuidanceApplyMode;
    branch: string;
    baseBranch?: string;
    worktreePath?: string;
    commit?: string;
    remote?: string;
    prUrl?: string;
    changedFiles?: string[];
    previousFiles?: Array<{
      file: string;
      relativePath: string;
      existed: boolean;
      content?: string;
    }>;
    appliedDirectly?: boolean;
    revertedAt?: number;
    pushed: boolean;
    error?: string;
  };
}

export interface SyncedReviewDecision {
  reportId: string;
  findingId: string;
  state: Exclude<ActionState, "open">;
  updatedAt: number;
  sourceDeviceId: string;
  sourceDeviceName?: string;
}

/** Basis for the activity window a health review covered. */
export type WindowBasis = "since-last-review" | "last-24h";

/**
 * The slice of time a health review actually covered: everything since the last
 * review, capped at 24 hours. This is what makes a review a true incremental
 * review rather than a re-scan of all history.
 */
export interface ReviewWindow {
  /** Epoch ms — window start. */
  start: number;
  /** Epoch ms — window end (when the review ran). */
  end: number;
  basis: WindowBasis;
  /** Human label, e.g. "Since 9:40 PM · 3h 12m of activity". */
  label: string;
  /** Sessions with activity inside the window. */
  sessionsInWindow: number;
  /** User+agent turns inside the window. */
  turnsInWindow: number;
}

/** A per-project rollup of what happened inside the review window. */
export interface ProjectInsight {
  name: string;
  path: string;
  sources: AnalysisSource[];
  sessions: number;
  turns: number;
  /** Rapid user follow-ups / corrections. */
  corrections: number;
  /** Tool calls that surfaced an error. */
  toolFailures: number;
  /** Agent uncertainty signals. */
  hedges: number;
  /** 0..100 local alignment for this project alone. */
  alignment: number;
  /** Top recurring topics, most frequent first. */
  topics: string[];
  hasAgentsMd: boolean;
  hasClaudeMd: boolean;
  hasRulesMd?: boolean;
  skillCount: number;
  /** Deterministic context-load and memory hygiene signal. */
  contextHealth?: ContextHealth;
}

export type ReviewDataMode = "demo" | "real";
export type ReviewGenerator = "demo-fixture" | "local-ingest" | "no-data";
export type ReviewCliStatus =
  | "not-required"
  | "skipped"
  | "executed"
  | "failed";

/** Provenance for whether a review came from demo fixtures or real local data. */
export interface ReviewProvenance {
  mode: ReviewDataMode;
  generator: ReviewGenerator;
  /** Must stay false outside explicit Demo Mode. */
  usedSampleData: boolean;
  sources: AnalysisSource[];
  generatedAt: number;
  cli: {
    invoked: boolean;
    status: ReviewCliStatus;
    runner?: string;
    model?: string;
    redactions?: number;
    payloadChars?: number;
    projects?: number;
    error?: string;
  };
}

/** Decisions captured during review, keyed by finding id. */
export type ReviewDecisions = Record<string, ActionState>;

/** User-facing lifecycle for a health report. */
export type HealthReviewStatus = "unreviewed" | "reviewed" | "expired";

export type ExperimentStatus = "proposed" | "running" | "concluded";
export type ExperimentVerdict = "helped" | "no-change" | "worse";
export type GoalDisposition = "kept" | "retired";

export interface Experiment {
  id: string;
  title: string;
  hypothesis: string;
  agentBenefit: string;
  userBenefit: string;
  reflection: string;
  metric: string;
  status: ExperimentStatus;
  /** 0..1 for tracked improvements ("4/5 sessions"). */
  progress?: number;
  progressLabel?: string;
  verdict?: ExperimentVerdict;
  verdictNote?: string;
  disposition?: GoalDisposition;
  /** Which project this goal targets, so the next review can measure it. */
  projectPath?: string;
  /** Where the accepted change landed. */
  category?: ActionCategory;
  /**
   * Snapshot of the target project at the moment the goal was accepted. The
   * next review compares against this to decide whether the change helped.
   */
  baseline?: { alignment: number; corrections: number; contextScore?: number };
}

/** The artifact a Health Review produces — styled like the Apple Health app. */
export interface HealthReport {
  id: string;
  /** Epoch ms the review completed — used for ordering and history labels. */
  timestamp: number;
  /** Full daily review or a faster same-day quick review. Defaults to full. */
  kind?: HealthReviewKind;
  /** Review lifecycle. Starting a newer review expires older unreviewed reports. */
  reviewStatus?: HealthReviewStatus;
  /** Epoch ms when the user marked the review reviewed. */
  reviewedAt?: number;
  /** Human label, e.g. "Last night · Jun 26". */
  rangeLabel: string;
  sessions: number;
  projects: number;
  harness: string;
  digest: string;
  rings: Ring[];
  metrics: Metric[];
  findings: Finding[];
  /** Tracked suggested improvements; stored as experiments for measurement. */
  experiments: Experiment[];
  /** Persisted Health Review decisions, if the user has reviewed it. */
  reviewDecisions?: ActionQueueEntry[];
  /** Human ↔ Agent alignment detail; optional — UI derives a fallback if absent. */
  alignment?: AlignmentDetail;
  /** The activity window this review covered (since last review, capped 24h). */
  window?: ReviewWindow;
  /** Per-project rollups inside the window, most active first. */
  projectInsights?: ProjectInsight[];
  /** Report-level context hygiene summary across reviewed projects. */
  contextHealth?: {
    score: number;
    status: ContextHealthStatus;
    overloadedProjects: number;
    riskCount: number;
    chars: number;
    memoryFiles: number;
    skillCount: number;
    suggestions: string[];
  };
  /** Redacted CLI payload summary for opt-in AI insight analysis. */
  cloudRedactionPreview?: {
    runner: string;
    model: string;
    redactions: number;
    payloadChars: number;
    projects: number;
    error?: string;
  };
  /** Real/demo and CLI execution provenance for this generated review. */
  provenance?: ReviewProvenance;
}

export interface HealthReviewStage {
  at: number;
  label: string;
}

export type TimeOfDay = "morning" | "midday" | "evening" | "night";

export type MomentKind =
  | "running"
  | "review"
  | "quick"
  | "full"
  | "rest"
  | "standby";
